# Generated by Django 4.1.7 on 2023-05-06 14:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('code', 'Code'), ('token', 'Token'), ('resource', 'Resource')], max_length=255, unique=True)),
                ('base_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'endpoint',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('disabled', models.BooleanField(default=False)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255, null=True)),
                ('public_key', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delimiter', models.CharField(choices=[('space', 'Space'), ('comma', 'Comma'), ('period', 'Period')], default='space', max_length=255)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), size=None)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='api.provider')),
            ],
            options={
                'db_table': 'scope',
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='provider_name_816b21_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['disabled'], name='provider_disable_7e6278_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['client_id'], name='provider_client__2c8a28_idx'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.endpoint'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api.provider'),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['provider'], name='scope_provide_dc9f63_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['name'], name='parameter_name_49eb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['endpoint'], name='parameter_endpoin_2fe2f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('endpoint', 'name'), name='parameter_endpoint_name_unique_index'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['provider'], name='endpoint_provide_607ff2_idx'),
        ),
    ]
