# Generated by Django 4.1.7 on 2023-04-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('code', 'Code'), ('token', 'Token'), ('resource', 'Resource')], max_length=255)),
                ('http_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete')], max_length=255)),
                ('base_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'endpoint',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='provider_name_816b21_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['disabled'], name='provider_disable_7e6278_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('name',), name='provider_name_unique_index'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.endpoint'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api.provider'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['endpoint'], name='parameter_endpoin_2fe2f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='parameter_name_value_unique_index'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['provider'], name='endpoint_provide_607ff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('type',), name='endpoint_type_unique_index'),
        ),
    ]
